name: Build AppImage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget fuse libfuse2

      - name: Download AppImage tools
        run: |
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool

      - name: Download LÖVE AppImage
        run: |
          wget -O love.AppImage "https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage"
          chmod +x love.AppImage

      - name: Create game bundle
        run: |
          mkdir -p dist/AppImage
          cd src
          zip -r ../dist/AppImage/game.love ./*
          cd ../dist/AppImage

      - name: Create AppDir structure
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp ../../.github/appimage/ClickShot.desktop AppDir/usr/share/applications/
          cp ../../.github/appimage/ClickShot.png AppDir/usr/share/icons/hicolor/256x256/apps/
          cp game.love AppDir/usr/bin/
          cp ../../love.AppImage AppDir/usr/bin/love

      - name: Create AppImage
        run: |
          ./appimagetool AppDir dist/AppImage/ClickShot-x86_64.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-appimage
          path: dist/AppImage/ClickShot-x86_64.AppImage 