name: Build ClickShot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download LÖVE 64-bit
        run: |
          curl -Lo love-win64.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
          tar -xf love-win64.zip

      - name: Make dist folder
        run: mkdir dist

      - name: Build .love file
        run: powershell -Command "Compress-Archive -Path src/* -DestinationPath dist/ClickShot.zip; Rename-Item dist/ClickShot.zip ClickShot.love"

      - name: Bundle ClickShot.exe (64-bit)
        run: |
          mkdir dist/Windows64
          copy dist\ClickShot.love love-11.5-win64\* dist\Windows64\
          ren dist\Windows64\love.exe ClickShot.exe

      - uses: actions/upload-artifact@v4
        with:
          name: clickshot-windows64
          path: dist/Windows64/

  build-windows-32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download LÖVE 32-bit
        run: |
          curl -Lo love-win32.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win32.zip
          tar -xf love-win32.zip

      - name: Make dist folder
        run: mkdir dist

      - name: Build .love file
        run: powershell -Command "Compress-Archive -Path src/* -DestinationPath dist/ClickShot.zip; Rename-Item dist/ClickShot.zip ClickShot.love"

      - name: Bundle ClickShot.exe (32-bit)
        run: |
          mkdir dist/Windows32
          copy dist\ClickShot.love love-11.5-win32\* dist\Windows32\
          ren dist\Windows32\love.exe ClickShot.exe

      - uses: actions/upload-artifact@v4
        with:
          name: clickshot-windows32
          path: dist/Windows32/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install FUSE
        run: sudo apt update && sudo apt install -y libfuse2

      - name: Run Linux compile script
        run: bash ./compile_linux.sh

      - uses: actions/upload-artifact@v4
        with:
          name: clickshot-linux
          path: dist/Linux/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run macOS compile script
        run: bash ./compile_macos.sh

      - uses: actions/upload-artifact@v4
        with:
          name: clickshot-macos
          path: dist/macOS/

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt update
          sudo apt install -y default-jdk zipalign

      - name: Clone Android Template
        run: |
          git clone https://github.com/ApeXPloit-Studios/ClickShot-Android.git android-build

      - name: Build .love file
        run: |
          mkdir -p android-build/love_decoded/assets
          zip -r android-build/love_decoded/assets/main.love src/

      - name: Build and Sign APK
        working-directory: android-build
        run: |
          java -jar apktool.jar b love_decoded -o ClickShot-unsigned.apk
          java -jar uber-apk-signer.jar --apks ClickShot-unsigned.apk

      - uses: actions/upload-artifact@v4
        with:
          name: clickshot-android
          path: android-build/apksigned/*.apk
