name: Build ClickShot

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Windows Compile Script
        run: ./compile_win64.bat

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-windows
          path: dist/Windows/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./compile_macos.sh
      - run: ./compile_macos.sh

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-macos
          path: dist/macOS/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Prepare AppImage Tool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage -O appimagetool.AppImage
          chmod +x appimagetool.AppImage

      - name: Run Linux Compile Script
        run: chmod +x ./compile_linux.sh && ./compile_linux.sh

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-linux
          path: dist/Linux/ClickShot.AppImage

  build-love2d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Love2D Package
        run: |
          mkdir -p dist/Love2D
          cd src
          zip -r ../dist/Love2D/ClickShot.love ./*

      - name: Upload Love2D Package
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D/ClickShot.love

  build-android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # or '17' for LTS, adjust as needed

      - name: Build .love bundle
        run: |
          mkdir -p dist/Love2D
          cd src
          powershell Compress-Archive -Path * -DestinationPath ../dist/Love2D/game.zip
          cd ../dist/Love2D
          ren game.zip game.love
          cd ../..

      - name: Clone Android build tools repo
        run: |
          git clone https://github.com/ApeXPloit-Studios/ClickShot-Android.git build/ClickShot-Android

      - name: Copy .love to assets
        run: |
          copy dist\Love2D\game.love build\ClickShot-Android\love_decoded\assets\main.love

      - name: Rebuild APK with apktool
        run: |
          cd build\ClickShot-Android
          java -jar apktool.jar b love_decoded -o ClickShot-unsigned.apk

      - name: Sign APK
        run: |
          cd build\ClickShot-Android
          java -jar uber-apk-signer.jar --apks ClickShot-unsigned.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-android
          path: build/ClickShot-Android/apksigned/ClickShot-unsigned-aligned-signed.apk
