name: Build ClickShot

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - run: chmod +x ./compile_macos.sh
      - run: ./compile_macos.sh

      - name: Zip macOS Build
        run: |
          cd dist
          zip -r ClickShot-macos.zip macOS
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-macos
          path: dist/ClickShot-macos.zip

  build-love2d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Create Love2D Package
        run: |
          mkdir -p dist/Love2D
          cd src
          zip -r ../dist/Love2D/ClickShot.love ./*
          cd ../dist/Love2D
          zip ClickShot-love2d.zip ClickShot.love
      - name: Upload Love2D Package
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D/ClickShot-love2d.zip

  build-android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build .love bundle
        run: |
          mkdir -p dist/Love2D
          cd src
          powershell Compress-Archive -Path * -DestinationPath ../dist/Love2D/game.zip
          cd ../dist/Love2D
          ren game.zip game.love
          cd ../..
      - name: Clone Android build tools repo
        run: |
          git clone https://github.com/ApeXPloit-Studios/ClickShot-Android.git build/ClickShot-Android
      - name: Copy .love to assets
        run: |
          copy dist\Love2D\game.love build\ClickShot-Android\love_decoded\assets\
      - name: Rebuild APK with apktool
        run: |
          cd build\ClickShot-Android
          java -jar apktool.jar b love_decoded -o ClickShot-unsigned.apk
      - name: Sign APK
        run: |
          cd build\ClickShot-Android
          java -jar uber-apk-signer.jar --apks ClickShot-unsigned.apk
      - name: Zip Signed APK
        run: powershell Compress-Archive -Path build\ClickShot-Android\*-aligned-*.apk -DestinationPath dist\ClickShot-android.zip

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-android
          path: dist\ClickShot-android.zip

  build-nintendo:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build 3DS Version
        run: |
          .\compile_nintendo.bat 3ds
      - name: Build Switch Version
        run: |
          .\compile_nintendo.bat switch
      - name: Build WiiU Version
        run: |
          .\compile_nintendo.bat wiiu

      - name: Zip Nintendo Builds
        run: |
          cd dist/Nintendo
          powershell Compress-Archive -Path * -DestinationPath ../ClickShot-nintendo.zip

      - name: Upload Nintendo Builds
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-nintendo
          path: dist/ClickShot-nintendo.zip
