name: Love Potion Builds

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-love2d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Create Love2D Package
        run: |
          mkdir -p dist/Love2D
          cd src
          zip -r ../dist/Love2D/ClickShot.love ./*
          cd ../dist/Love2D
          zip ClickShot-love2d.zip ClickShot.love

      - name: Upload Love2D Package
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D/ClickShot-love2d.zip

  build-switch:
    needs: build-love2d
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Love2D Package
        uses: actions/download-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D

      - name: Set up devkitPro + LovePotion for Switch
        run: |
          sudo apt-get update
          sudo apt-get install -y zip git wget curl python3-pip
          wget https://apt.devkitpro.org/install-devkitpro-pacman -O install-dkp.sh
          chmod +x install-dkp.sh
          sudo ./install-dkp.sh
          echo "[dkp-libs]
          Server = https://downloads.devkitpro.org/packages" | sudo tee -a /etc/pacman.conf
          sudo dkp-pacman -Sy --noconfirm switch-dev
          git clone https://github.com/Hydr8gon/lovebrew.git
          cd lovebrew && make && sudo cp build/lovebrew /usr/local/bin && cd ..

      - name: Build for Switch
        run: |
          mkdir -p dist/Switch
          cd dist/Love2D
          unzip ClickShot-love2d.zip
          cd ../..
          lovebrew -i dist/Love2D/ClickShot.love -o dist/Switch/ClickShot.nro --title "ClickShot" --author "ApeXPloit Studios"

      - name: Upload Switch Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-switch
          path: dist/Switch/ClickShot.nro

  build-3ds:
    needs: build-love2d
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Love2D Package
        uses: actions/download-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D

      - name: Set up devkitPro + LovePotion for 3DS
        run: |
          sudo apt-get update
          sudo apt-get install -y zip git wget curl python3-pip
          wget https://apt.devkitpro.org/install-devkitpro-pacman -O install-dkp.sh
          chmod +x install-dkp.sh
          sudo ./install-dkp.sh
          echo "[dkp-libs]
          Server = https://downloads.devkitpro.org/packages" | sudo tee -a /etc/pacman.conf
          sudo dkp-pacman -Sy --noconfirm 3ds-dev

      - name: Build for 3DS
        run: |
          mkdir -p dist/3DS
          cd dist/Love2D
          unzip ClickShot-love2d.zip
          cd ../..
          cp dist/Love2D/ClickShot.love dist/3DS/boot.love
          cp dist/3DS/boot.love dist/3DS/ClickShot.3dsx

      - name: Upload 3DS Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-3ds
          path: dist/3DS/ClickShot.3dsx

  build-wiiu:
    needs: build-love2d
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Love2D Package
        uses: actions/download-artifact@v4
        with:
          name: clickshot-love2d
          path: dist/Love2D

      - name: Set up devkitPro + LovePotion for Wii U
        run: |
          sudo apt-get update
          sudo apt-get install -y zip git wget curl python3-pip
          wget https://apt.devkitpro.org/install-devkitpro-pacman -O install-dkp.sh
          chmod +x install-dkp.sh
          sudo ./install-dkp.sh
          echo "[dkp-libs]
          Server = https://downloads.devkitpro.org/packages" | sudo tee -a /etc/pacman.conf
          sudo dkp-pacman -Sy --noconfirm wiiu-dev
          git clone https://github.com/TurtleP/LovePotion.git
          cd LovePotion
          make wiiu
          cd ..

      - name: Build for Wii U
        run: |
          # Create proper Cemu folder structure
          mkdir -p dist/WiiU/ClickShot/{code,content,meta}
          
          # Copy the .love file to content
          cd dist/Love2D
          unzip ClickShot-love2d.zip
          cd ../..
          cp dist/Love2D/ClickShot.love dist/WiiU/ClickShot/content/game.love
          
          # Copy the compiled RPX to code
          cp LovePotion/build/wiiu/main.rpx dist/WiiU/ClickShot/code/
          
          # Create proper meta.xml
          cat > dist/WiiU/ClickShot/meta/meta.xml << EOL
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
          <menu>
            <id>00050000101C5A00</id>
            <version>1.0.0</version>
            <type>1</type>
            <os_version>0x000500101000000A</os_version>
            <title>
              <id>00050000101C5A00</id>
              <version>1.0.0</version>
              <type>1</type>
              <name>ClickShot</name>
              <author>ApeXPloit Studios</author>
              <path>code/main.rpx</path>
            </title>
          </menu>
          EOL

      - name: Upload Wii U Build
        uses: actions/upload-artifact@v4
        with:
          name: clickshot-wiiu
          path: dist/WiiU/ClickShot/**
